spin_manifest_version = 2

[application]
name = "static"
version = "0.1.1"
authors = ["jlcanela <jlcanelam@gmail.com>"]
description = ""

[[trigger.http]]
route = "/api/config"
component = "backend"

[variables]
auth0_client_id = { required = true }
auth0_domain = { required = true }

[[trigger.http]]
route = "/..."
component = "static"

[component.static]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "frontend/dist", destination = "/" }]
environment = { FALLBACK_PATH = "index.html" }

[component.static.build]
command = "trunk build --config frontend/Trunk.toml"
watch = ["frontend/src/**/*.rs", "frontend/Cargo.toml", "frontend/Trunk.toml"]

[component.backend]
source = "target/wasm32-wasi/release/backend.wasm"
allowed_outbound_hosts = []

[component.backend.build]
command = "cargo build -p backend --target wasm32-wasi --release"
watch = ["backend/src/**/*.rs", "backend/Cargo.toml"]

[component.backend.variables]
auth0_client_id = "{{ auth0_client_id }}"
auth0_domain = "{{ auth0_domain }}"
